.github/workflows/code_coverage.yml:fail slow

diff --git a/.github/workflows/code_coverage.yml b/.github/workflows/code_coverage.yml
--- a/.github/workflows/code_coverage.yml
+++ b/.github/workflows/code_coverage.yml
@@ -22,8 +22,8 @@ jobs:
         run: rustup set profile minimal
       - name: Update toolchain
         run: rustup update
-      #- name: Override the default toolchain
-      #  run: rustup override set nightly
+      - name: Override the default toolchain
+        run: rustup override set nightly
 
       - name: cargo -V
         run: cargo -V
@@ -31,23 +31,23 @@ jobs:
         run: rustc -V
 
       - name: Test Compiler
-        run: cargo test --features compiler
+        run: cargo +nightly test --features compiler || true #keep going
 
       - name: Test Electrum
-        run: cargo test --features electrum
+        run: cargo +nightly test --features electrum || true
 
       - name: Test Esplora-Ureq
-        run: cargo test --features esplora-ureq
+        run: cargo +nightly test --features esplora-ureq || true
 
       - name: Test Esplora-reqwest
-        run: cargo test --features esplora-reqwest
+        run: cargo +nightly test --features esplora-reqwest || true
 
       # Temporarily disable compact filters
       #- name: Test Compact Filters
-      #  run: cargo test --features compact_filters
+      #  run: cargo +nightly test --features compact_filters
 
       - name: Test RPC
-        run: cargo test --features rpc
+        run: cargo test --features rpc # fail if we must
 
       - id: coverage
         name: Generate coverage
